cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_from_cart_view, name='cart_remove'),
    path('clear/', views.clear_cart, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('pages.urls')),
    path('', include('products.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),

    # rosetta
    path('rosetta/', include('rosetta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment_create'),

]

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from ckeditor.fields import RichTextField


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('name'))
    description = RichTextField()
    short_description = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    active = models.BooleanField(default=True)
    image = models.ImageField(verbose_name=_('Product image'), upload_to='product/product_cover/', blank=True)

    datetime_created = models.DateTimeField(default=timezone.now())
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.id])


# class ActiveCommentsManager(models.Manager):
#     def get_queryset(self):
#         return super(ActiveCommentsManager, self).get_queryset().filter(active=True)


class Comment(models.Model):
    PRODUCT_STARS = [
        ('1', _('Awful')),
        ('2', _('Bad')),
        ('3', _('Normal')),
        ('4', _('Good')),
        ('5', _('Perfect')),
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments', verbose_name=_('Comment Author'))
    body = models.TextField(verbose_name=_('Comment Text'))
    active = models.BooleanField(default=True)
    stars = models.CharField(max_length=10, choices=PRODUCT_STARS, verbose_name=_('Your Score'))

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    # Manager
    # object = models.Manager
    # active_comments_manager = ActiveCommentsManager()

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.product.id])

products/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', 'stars', ]

products/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.utils.translation import gettext as _
from django.contrib import messages

from .models import Product, Comment
from .forms import CommentForm
from cart.forms import AddToCartProductForm


class ProductListView(generic.ListView):
    model = Product
    queryset = Product.objects.filter(active=True)
    template_name = 'products/product_list.html'
    context_object_name = 'products'


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm
        context['add_to_cart_form'] = AddToCartProductForm
        return context


class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user

        product_id = int(self.kwargs['pk'])
        product = get_object_or_404(Product, id=product_id)

        obj.product = product

        messages.success(self.request, _('Your comment added successfully.'))

        return super(CommentCreateView, self).form_valid(form)

products/templates/products/product_list.html
{% extends '_base.html' %}

{% load persian_translation_tags %}
{% load humanize %}
{% load i18n %}

{% block page_title %}لیست محصولات{% endblock page_title %}

{% block content %}

    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper container-fluid">
        <div class="shop-page-wrapper shop-fullwidth">
            <div class="container">
                <div class="row mb--50">
                    <div class="col-12">
                        <div class="shop-toolbar">
                            <div class="container row align-items-center">
                                <div class="col-lg-12 mb-md--50 mb-xs--10">
                                    <div class="shop-toolbar__left d-flex align-items-sm-center align-items-start flex-sm-row flex-column">
                                        <p class="product-pages">نمایش ۱-۲۰ از ۴۹</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid shop-products">
                <div class="row">
                    <div class="col-12">
                        <div class="tab-content" id="product-tab-content">
                            <div class="tab-pane fade show active" id="nav-all">
                                <div class="row xxl-block-grid-6 grid-space-20">
                                    {% for product in products %}
                                        <div class="col-xl-3 col-md-4 col-sm-6 mb--50">
                                            <div class="ShoppingYar-product">
                                                <div class="product-inner">
                                                    <figure class="product-image">
                                                        <a href="{{ product.get_absolute_url }}">
                                                            {% if product.image %}
                                                                <img src="{{ product.image.url }}" alt="Products">
                                                            {% endif %}
                                                        </a>
                                                        <div class="ShoppingYar-product-action">
                                                            <div class="product-action d-flex">
                                                                <a href="wishlist.html" class="action-btn">
                                                                    <i class="flaticon flaticon-like"></i>
                                                                </a>
                                                            </div>
                                                        </div>
                                                        <span class="product-badge">تخفیف ویژه</span>
                                                    </figure>
                                                    <div class="product-info">
                                                        <h3 class="product-title h6 mb--15">
                                                            <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                                        </h3>
                                                        <div class="product-price-wrapper mb--30">
                                                            <span class="money text-success">{{ product.price|intcomma:False|translate_number }} {% trans '$' %}</span>
                                                            <span class="money-separator">-</span>
                                                            <span class="old-price text-danger">
                                                        <span class="money text-danger">۸۰,۰۰۰ {% trans '$' %}</span>
                                                    </span>
                                                        </div>
                                                        <form action="{% url 'cart:cart_add' product.id %}"
                                                              method="post">
                                                            {% csrf_token %}
                                                            <div class="quantity-wrapper">

                                                                <input type="hidden" class="quantity-input"
                                                                       name="quantity" id="qty" value="1"
                                                                       min="1" max="30">

                                                                <button type="submit"
                                                                        class="btn btn-small btn-bg-red btn-color-white btn-hover-2">
                                                                    {% trans 'add to cart' %}
                                                                </button>
                                                                {#                                                        <a href="{% url 'cart:cart_detail' %}" type="submit" class="btn btn-small btn-bg-red btn-color-white btn-hover-2">#}
                                                                {#                                                            {% trans 'add to cart' %}#}
                                                                {#                                                        </a>#}
                                                            </div>
                                                        </form>
                                                        {#                                                <a href="cart.html" class="btn btn-small btn-bg-sand btn-color-dark px-3">اضافه کردن به سبد خرید</a>#}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>


                        <nav class="pagination-wrap mt--35 mt-md--25 pb-5">
                            <ul class="pagination">
                                <li><a href="#" class="next page-number"><i class="fa fa-angle-double-right"></i></a>
                                </li>
                                <li><span class="current page-number">1</span></li>
                                <li><a href="#" class="page-number">2</a></li>
                                <li><a href="#" class="page-number">3</a></li>
                                <li><a href="#" class="prev page-number"><i class="fa fa-angle-double-left"></i></a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->

    {% include 'cart/cart_sidebar.html' %}

{% endblock content %}